server:
  port: 8080
  address: 0.0.0.0
spring:
  thymeleaf.cache: false
  resources.static-locations: 
    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
    - file:${system.store}
  jpa:
    hibernate.ddl-auto: update
#    hibernate.dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    #url: jdbc:h2:file:~/.h2/camaraplat;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;
    #url: jdbc:mysql://192.168.123.12:3306/camera?autoReconnect=true&useSSL=false
    url: jdbc:mysql://localhost:3306/camera?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: root
logging:
  level:
    root: INFO
    org.springframework.web: WARN
    io.moquette: WARN
    messageLogger: WARN
    org.springframework.security: WARN
system:
  store: E://camera/picture_store/
  store.snapshot: ${system.store}snapshot
  store.people: ${system.store}people
faceservice:
  bathPath: http://localhost:8081
  oauth: 
    apiKey: faceplat_user
    apiSecret: faceplat
    username: admin
    password: admin
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
