server:
  port: 8081
  address: 0.0.0.0
spring.application.name: face-plat
spring:
  http.multipart.max-file-size: 10500KB
  redis:
    host: localhost
    port: 6379
    database: 8
#    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
      timeout: 0
algorithm:
  serverAddress:
    - 192.168.123.222:11011
  client:
    service: com.minivision.faceplat.thrift.Serv
    maxActive: 8
    idleTime: 180000
  param:
    scoreLevels:
      - 3.95
      - 4.68
      - 8.63
face:
  image:
    path: c:/minivision/
    save: false
    remove: false
security:
  oauth2:
    client:
      client-id: faceplat_user
      client-secret: faceplat
  user:
    name: admin
    password: admin
management:
  security.enabled: false
info:
  id: faceplat
  version: 0.0.1-snapshot
logging.path: logs
