server:
  port: 8081
  address: 0.0.0.0
spring:
  redis:
    host: 192.168.123.12
    port: 6379
#    password: 
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
      timeout: 0
algorithm:
  serverAddress:
    - 192.168.123.17:9008
    - 192.168.123.17:9009
  client:
    service: com.minivision.faceplat.thrift.Serv
    maxActive: 16
    idleTime: 180000
  param:
    scoreLevels:
      - 3.46
      - 5.0
      - 9.0
face:
  image:
    path: d:/minivision/
    save: true
    remove: true